### PR TITLE
Agents

### PR DESCRIPTION
**Pull request by ellarauth**
Stuff I've added:
- mechanics for checking if intruders have reached their target
- mechanics for terminating the simulation if the guards or intruders won
- PatrollingGuard: guard that uses pathfinding for patrolling between 3 randomly selected (without repetition) cornerpoints of the board (can be changed to any points on the board but i thought this made the most sense when using the maze) and chasing intruders

### CODE REVIEW

**Comment by Evelyn-H** [comment]
Assuming all the capturing logic and such is correct this is really good :)
Only thing I'm not 100% about is calling the `Agent.on
_captured` in the `World._capture_check` just because I like calling all the agent event handlers from the `Agent.tick` method, but it is a lot shorter and simpler, so it's probably fine.

(Using an ECS would've been perfect for this project, but alas, it's a bit restrictive if you haven't used it before so I don't wanna impose that on the group :p)

**Review by Evelyn-H — APPROVED** [review]
Good, good!

**Comment by ellarauth** [comment]
Thanks! 

I get why you'd prefer calling `Agent.on_captured` from `Agent.tick`. I actually tried that at first but it was a bit difficult to get everything to be executed excatly once, so I decided to move it in the end. However, I also think that using variables like `_prev_is_captured` is not super elegant. Maybe there's some other way of doing this?

What's an ECS?

**Comment by Evelyn-H** [comment]
The easiest way to solve that would probably be to have some sort of method for agents that receives and stores events (captured, collided, target reached, ...) and then process those in the `Agent.tick` method. That way we can both generate events from wherever we want *and* handle them all in the `Agent.tick` method.

And an ECS = Entity Component System. It's a really clean and interesting way to do game / simulation programming that is much more easy to modify and avoids a lot of spaghetti code.

**Pull request merged**
