### PR TITLE
Vision

### PR DESCRIPTION
**Pull request by ellarauth**

### CODE REVIEW

**Comment by ellarauth** [comment]
vision of structures is still missing but i think it would be good to merge these two branches before i work on the patrolling guard

can you maybe look at the second to-do item (about an indexing problem) in the agent file (i think it's line 336)? i couldn't figure out the indexing of the map so i just guessed that the coordinates for current_tile start indexing at 1 and the map starts indexing at 0. that seemed to solve the issue but i just want to be sure it's correct

**Comment by Evelyn-H** [comment]
The indexing should start at 0, it's just a numpy array, could you double check that the agent isn't somehow out of bounds when that happens?
If not, let me know and I'll look into it a bit deeper

**Comment by ellarauth** [comment]
i've seen that the agent is out of bounds when that happens but i noticed that the rest of the code still runs perfectly fine even then, just this one line causes problems in those situations

**Comment by Evelyn-H** [comment]
Might wanna add a method to the Map class to get the vision modifier of a tile with a bounds check, I think I've done that for the walls and such, which is probably why the rest still works fine

**Comment by ellarauth** [comment]
That sounds like a cleaner solution than what I have now, I'll look into it

**Pull request merged**
